# Generated by Django 4.2.26 on 2025-12-03 16:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Orszag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nev', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Telepules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nev', models.CharField(max_length=255)),
                ('OId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='latvanyossagok.orszag')),
            ],
        ),
        migrations.CreateModel(
            name='Latvanyossag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nev', models.CharField(max_length=255)),
                ('RLeiras', models.TextField()),
                ('AtlagErtekeles', models.DecimalField(decimal_places=3, default=0.5, max_digits=3)),
                ('Nyitvatartas', models.CharField(max_length=255)),
                ('URL', models.URLField()),
                ('VId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='latvanyossagok.telepules')),
            ],
        ),
        migrations.CreateModel(
            name='Hozzaszolasok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Megjegyzes', models.TextField()),
                ('Iro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('LId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='latvanyossagok.latvanyossag')),
            ],
        ),
    ]
