# Generated by Django 4.2.26 on 2025-12-04 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('latvanyossagok', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='latvanyossag',
            name='Nyitvatartas',
            field=models.CharField(default='H-P: 07-19, SZ: 10-14, V: zárva', max_length=255),
        ),
    ]
