# Generated by Django 4.2.26 on 2025-12-05 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('latvanyossagok', '0002_alter_latvanyossag_nyitvatartas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='latvanyossag',
            name='AtlagErtekeles',
            field=models.DecimalField(decimal_places=2, default=0.5, max_digits=5),
        ),
    ]
